baseurl = "https://krandor.business/"
title = "Krandor Home"
languageCode = "en-uk"

# Theme to use
theme = "simple"

# Pagination
paginate = 21
paginatePath = "page"

# Google analytics
googleAnalytics = "UA-131728687-1"

# Copyright
copyright = "© 2019 — The Real Krandor  — All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/post/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/recipes/"
    name = "recipes"
    weight = 2
  [[menu.main]]
    url = "/docs/"
    name = "docs"
    weight = 3
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 4

  # Footer
  [[menu.footer]]
    url = "https://github.com/Xzya"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "/post/index.xml"
    name = "RSS"
    weight = 2

# Links format
[permalinks]
  post = "/post/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
